### ISSUE TITLE
Making FFMUC's backend compatible with the upstream wireguard implementation

### ISSUE THREAD

**Issue by GoliathLabs** [freifunk-gluon/community-packages#18]
Hello,
as we discussed at the Gluon RC3 meetup, we from Freifunk München would like to make our backend compatible with the current Gluon integration of the wireguard protocol. It was mentioned in the HedgeDoc that @lemoer could help us with this and we would greatly appreciate it. It would be great if we could discuss the migration process and next steps in our Mattermost chat (https://chat.ffmuc.net).

Thank you very much for your great work!

**Comment by goligo** [comment]
I doubt Gluon has a custom implementation of the wireguard protocol. I guess you mean with the current integration of the wireguard protocol in Gluon?

**Comment by GoliathLabs** [comment]
Yeah. Changed that in my comment above. Thanks for pointing that out
