### ISSUE TITLE
[suggestion] Add Offline-SSID-Changer using gluon has_default_gw

### ISSUE THREAD

**Issue by maurerle** [freifunk-gluon/community-packages#27]
It would be very good to have an Offline-SSID-Changer package available here.
It should work with BATMAN_IV, BATMAN_V and babel

existing repos from single communities are:
- https://github.com/freifunk-kiel/gluon-ssid-notifier/
- #9  (mesh protocol agnostic)
- https://github.com/eulenfunk/packages/tree/v2020.1.x/gluon-ssid-changer
- https://github.com/ffac/gluon-ssid-changer/
- https://github.com/Freifunk-Nord/gluon-ssid-changer
- https://gitlab.freifunk-stuttgart.de/firmware/gluon-ssid-changer
- https://github.com/tecff/gluon-packages/tree/main/tecff-ssid-changer (supports has_default_gw and owe)

A [try to put something like this upstream](https://github.com/freifunk-gluon/gluon/pull/1649) failed, so I think it would be best to have this package here.

Recently gluon got a mesh-agnostic way to receive the online state and neighbours:
- https://github.com/freifunk-gluon/gluon/issues/2228

So it would be cool to have a package which relies on this functionality.

**Comment by rotanid** [comment]
> Recently gluon got a mesh-agnostic way to receive the online state and neighbours:
> 
>     * [gluon-online-status concept gluon#2228](https://github.com/freifunk-gluon/gluon/issues/2228)
> 
> 
> So it would be cool to have a package which relies on this functionality.

this does not replace much of the functionality in most of these ssid-changer solutions.
have a look at https://github.com/tecff/gluon-packages/commit/0e5f16f5b1ac12e20412f50ebdcc11f566c56f5f and you can see how little this changes.
