### ISSUE TITLE
Add ffho-ap-timer and ffho-web-ap-timer

### ISSUE THREAD

**Issue by maurerle** [freifunk-gluon/community-packages#37]
These two packages seem quite valuable and are used across communities.
So it makes sense to add them here.

This would also allow to decrease the list of different module sources in FFMUC, as all used packages are then available in the community-packages repository.

Packages are currently available here:
https://github.com/FreifunkHochstift/ffho-packages/tree/master/ffho-web-ap-timer
https://github.com/FreifunkHochstift/ffho-packages/tree/master/ffho-ap-timer

**Comment by mkg20001** [comment]
The maintainers of the package can open a pull request and it will be merged into this repository
