### ISSUE TITLE
ffac-ssid-changer: SIGHUP does not change the SSID (OpenWrt 23.05.x)

### ISSUE THREAD

**Issue by hafu** [freifunk-gluon/community-packages#93]
With the update to gluon v2023.2.x (OpenWrt 23.05.x) the SSID does not change when the node is considered offline.

I've tested it with a new node with an initial configuration (`sysupgrad -n …`). With `debug_log_enabled` I could see that the node is considered offline and it even says that the SSID is changed to the configured prefix. The hostapd configuration is updated correctly (`/var/run/hostapd-phy*.conf`) but the SSID never changes.

I could reproduce this issue even with a vanilla OpenWrt:
- Change the SSID in `/var/run/hostapd-phy*.conf`
- Run `killall -HUP hostapd`
 
The SSID should change but it does not.

Any suggestions?

**Comment by maurerle** [comment]
Hi @hafu,
I just looked into this issue and found it reproducible.
A workaround is to use `ubus call hostapd reload` which does the same reload in https://w1.fi/cgit/hostap/tree/hostapd/main.c#n406

Though this is not backwards compatible.
I will try to create a better working version of this package in the coming weeks.
